### ISSUE TITLE
Android - viewport doesn't expand after keyboard is closed

### ISSUE THREAD

**Issue by gnesher** [ionic-team/cordova-plugin-ionic-keyboard#113]
Please see attached photos (taken via chrome inspector)
I've created a for, see the cancel/save button is floating at the bottom. I then open the keyboard and close it by selecting the "Main" button. 
The keyboard closes down, but the viewport does not update and the buttons are pushed up.

Happening on multiple Samsung devices.

![keyboardClosedPNG](https://user-images.githubusercontent.com/1402060/64111038-5a8fcd80-cd8c-11e9-95f4-bbe14bd1a70c.PNG)
![keyboardClosed2](https://user-images.githubusercontent.com/1402060/64111041-5bc0fa80-cd8c-11e9-819f-d941cb88ddf5.PNG)

**Comment by phihochzwei** [comment]
Same here

**Comment by phihochzwei** [comment]
Okay this "feels" like having a component set to ChangeDetectionStrategy.OnPush, to speak in Angular terms. I tried the ChangeDetector as well but no success: 

Quick and DIRTY workaround (I got a customer in my neck because this currently affects an app with has gone live 24 hours ago xD): Get the ion-app element, change its style inline to height:99% and after 200ms change it back to 100%. As mentioned: Dirty but keeps you going until there is a another fix.

**Comment by gnesher** [comment]
@phihochzwei thanks for that, I've ended up doing something similar. 
I've tried looking at the source code, I can't see anything that looks odd in their JS - I've got an odd feeling that the problem is not in the plugin itself

**Comment by phihochzwei** [comment]
@gnesher Personally I think it´s a problem of the webview. But thats just my opinion :)

**Comment by jcesarmobile** [comment]
This is a chrome 76 bug, it's been reported already on their tracker https://bugs.chromium.org/p/chromium/issues/detail?id=994807

This workaround seems to work
https://github.com/ionic-team/ionic/issues/19065#issuecomment-523423118
