### ISSUE TITLE
Ionic option select menu not working on ios device

### ISSUE THREAD

**Issue by hugorojasppm** [ionic-team/cordova-plugin-ionic-keyboard#85]
Im using ionic v1 with Angular. 
**My current list of installed corvova plugins are the following:**

sudo cordova plugin ls
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 3.1.2 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"

In the www/js/app.js I set: cordova.plugins.Keyboard.hideKeyboardAccessoryBar(false);
Yet, Im unable to select an option in a <select> tag.
This is happening only in iOS, is there an extra step that I'm missing?
How do I update that change when I deploy from xCode.

Thanks in advanced

**Comment by rodrigomoretto** [comment]
Try setting this in your config.xml like mencioned in #70 :
`<preference name="HideKeyboardFormAccessoryBar" value="false"/>`
Just tried this and it seems to work fine even on ionic 1;

**Comment by jcesarmobile** [comment]
Can you provide a sample app? I don't really know what do you mean bu "Ionic option select menu"

**Comment by rodrigomoretto** [comment]
If his problem was the same as mine (which I assumed it was because I was trying the same steps as his), then its a problem when you have a select tag on ionic 1 the keyboard will popup with the options available as a picker. The problem happens when you select the desired option, on android it works fine by just touching it, on iOS it does nothing. So I had to change those settings and show the FormAccessoryBar so it will show the done button to make the selection. I have been using ionic 1 just recently to maintain an old app, so I'm not sure if that feature was working properly before.

A simple way to test it is by simply creating a select with a few options and build it for iOS

`<div>
  <label>Select:
    <select>
      <option>Blue</option>
      <option>Red</option>
      <option>Green</option>
    </select>
  </label>
</div>`

**Comment by jcesarmobile** [comment]
Thanks for the input @rodrigomoretto 

I see the issue now, he is using `cordova.plugins.Keyboard.hideKeyboardAccessoryBar(false);`, but that's the old plugin API, in this plugin the API is `Keyboard.hideKeyboardAccessoryBar(false);`, or using the preference you mentioned, which wasn't documented, I recently documented it, so I'm going to close.
